#include "web_dashboard_page.h"

#include "config.h"

static const char g_dashboard_page[] =
    "HTTP/1.1 200 OK\r\n"
    "Content-Type: text/html\r\n"
    "Cache-Control: no-cache\r\n"
    "Connection: close\r\n"
    "\r\n"
    "<!DOCTYPE html><html><head>"
    "<meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<style>"
    "body{font-family:monospace;background:#0f172a;color:#e2e8f0;margin:0;padding:16px;}"
    "h1{margin:0 0 12px;font-size:1.4rem;}"
    ".stream{margin-bottom:12px;color:#f97316;}"
    ".panel{background:#111827;border:1px solid #334155;border-radius:10px;padding:12px;margin-bottom:12px;}"
    ".controls{margin-top:28px;}"
    ".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px;}"
    ".card{background:#111827;border:1px solid #334155;border-radius:10px;padding:12px;}"
    ".label{font-size:.8rem;color:#94a3b8;margin-bottom:6px;text-transform:uppercase;}"
    ".value{font-size:1.2rem;font-weight:bold;}"
    ".row{display:flex;gap:10px;flex-wrap:wrap;align-items:end;}"
    "label{display:flex;flex-direction:column;gap:4px;font-size:.85rem;color:#94a3b8;}"
    "input,select,button{font:inherit;border-radius:8px;border:1px solid #475569;padding:8px;background:#0f172a;color:#e2e8f0;}"
    "button{cursor:pointer;min-width:88px;}"
    ".hint{margin-top:10px;color:#94a3b8;}"
    ".safe{color:#4ade80;}.warn{color:#f97316;}.live{color:#38bdf8;}.bad{color:#fb7185;}"
    "</style></head><body>"
    "<h1>" ROBOT_NAME "</h1>"
    "<div id='stream' class='stream'>CONNECTING</div>"
    "<div class='grid'>"
    "<div class='card'><div class='label'>State</div><div id='state' class='value'>--</div></div>"
    "<div class='card'><div class='label'>Failsafe</div><div id='failsafe' class='value'>--</div></div>"
    "<div class='card'><div class='label'>Left</div><div id='left' class='value'>--</div></div>"
    "<div class='card'><div class='label'>Right</div><div id='right' class='value'>--</div></div>"
    "<div class='card'><div class='label'>Weapon</div><div id='weapon' class='value'>--</div></div>"
    "<div class='card'><div class='label'>Age</div><div id='age' class='value'>--</div></div>"
    "<div class='card'><div class='label'>Roll</div><div id='roll' class='value'>--</div></div>"
    "<div class='card'><div class='label'>Pitch</div><div id='pitch' class='value'>--</div></div>"
    "<div class='card'><div class='label'>Yaw</div><div id='yaw' class='value'>--</div></div>"
    "<div class='card'><div class='label'>Temp</div><div id='temp' class='value'>--</div></div>"
    "<div class='card'><div class='label'>Humidity</div><div id='hum' class='value'>--</div></div>"
    "<div class='card'><div class='label'>Test Run</div><div id='test-status' class='value'>IDLE</div></div>"
    "<div class='card'><div class='label'>Test Remaining</div><div id='test-remaining' class='value'>--</div></div>"
    "</div>"
    "<div class='panel controls'>"
    "<div class='label'>Safety</div>"
    "<div class='row'>"
    "<button id='state-toggle'>E-Stop</button>"
    "</div>"
    "<div id='state-result' class='hint'>ACTIVE allows controller input. STOPPED blocks it.</div>"
    "</div>"
    "<div class='panel'>"
    "<div class='label'>Motor Test</div>"
    "<div class='row'>"
    "<label>Motor<select id='test-motor'><option value='left'>left</option><option value='right'>right</option><option value='weapon'>weapon</option></select></label>"
    "<label>Seconds<input id='test-duration' type='number' min='0' step='0.1' value='2'></label>"
    "<label>Power %<input id='test-power' type='number' min='0' max='100' step='1' value='30'></label>"
    "<button id='test-start'>Start</button>"
    "<button id='test-stop'>Stop</button>"
    "</div>"
    "<div id='test-result' class='hint'>0 seconds means run until stopped.</div>"
    "</div>"
    "<script>"
    "const s=document.getElementById('state');"
    "const f=document.getElementById('failsafe');"
    "const l=document.getElementById('left');"
    "const r=document.getElementById('right');"
    "const w=document.getElementById('weapon');"
    "const a=document.getElementById('age');"
    "const ro=document.getElementById('roll');"
    "const p=document.getElementById('pitch');"
    "const y=document.getElementById('yaw');"
    "const te=document.getElementById('temp');"
    "const hu=document.getElementById('hum');"
    "const ts=document.getElementById('test-status');"
    "const tr=document.getElementById('test-remaining');"
    "const st=document.getElementById('stream');"
    "const sb=document.getElementById('state-toggle');"
    "const sr=document.getElementById('state-result');"
    "const tm=document.getElementById('test-motor');"
    "const td=document.getElementById('test-duration');"
    "const tp=document.getElementById('test-power');"
    "const tb=document.getElementById('test-result');"
    "function sc(v){if(v==='ACTIVE')return'live';if(v==='INIT')return'warn';return'safe';}"
    "function runReq(url,target){fetch(url,{cache:'no-store'}).then(async r=>({ok:r.ok,text:await r.text()})).then(x=>{target.textContent=x.text;target.className='hint '+(x.ok?'safe':'bad');}).catch(()=>{target.textContent='Request failed';target.className='hint bad';});}"
    "sb.onclick=()=>{runReq('/api/estop/toggle',sr);};"
    "document.getElementById('test-start').onclick=()=>{const power=Math.max(0,Math.min(100,Number(tp.value)||0));const duration=Math.max(0,Number(td.value)||0);runReq('/api/test/start?motor='+encodeURIComponent(tm.value)+'&power='+power+'&duration='+duration,tb);};"
    "document.getElementById('test-stop').onclick=()=>{runReq('/api/test/stop',tb);};"
    "const es=new EventSource('/events');"
    "es.onopen=()=>{st.textContent='CONNECTED';st.className='stream safe';};"
    "es.onmessage=e=>{const d=e.data.split(',');if(d.length!==15)return;"
    "s.textContent=d[0];s.className='value '+sc(d[0]);"
    "sb.textContent=d[0]==='ACTIVE'?'E-Stop':'Resume';"
    "f.textContent=d[1]==='1'?'TRIPPED':'CLEAR';f.className='value '+(d[1]==='1'?'bad':'safe');"
    "l.textContent=(Number(d[2])>=0?'+':'')+d[2]+'%';"
    "r.textContent=(Number(d[3])>=0?'+':'')+d[3]+'%';"
    "w.textContent=d[4]+'%';a.textContent=d[5]+' ms';"
    "ro.textContent=d[6]+' deg';p.textContent=d[7]+' deg';y.textContent=d[8]+' deg';"
    "ts.textContent=d[9]==='1'?(d[10]+' '+d[11]+'%'):'IDLE';"
    "ts.className='value '+(d[9]==='1'?'live':'safe');"
    "tr.textContent=d[9]==='1'?(d[12]==='0'?'HOLD':d[12]+' ms'):'--';"
    "te.innerHTML=Math.round(d[13]*9/5+32)+'&deg;F';hu.textContent=d[14]+'%';};"
    "es.onerror=()=>{st.textContent='RECONNECTING';st.className='stream warn';};"
    "</script></body></html>";

const char* web_dashboard_page_data(void) {
    return g_dashboard_page;
}

size_t web_dashboard_page_size(void) {
    return sizeof(g_dashboard_page) - 1;
}
